version: 2

general:
  branches:
    only:
      - student
jobs:
  build:
    docker:
      - image: romankhazanskii/circleci-alpine:0.0.3
    steps:
      - checkout
      - run:
          name: Check due date
          when: always
          command: chmod +x .test/date_checker.sh && .test/date_checker.sh
